title: WP Property
description: WP-Property is the most popular plugin for creating and managing highly customizable real estate, property management, and completely custom listing showcase websites.
logo_image: https://storage.googleapis.com/media.usabilitydynamics.com/2014/11/2c6fc7ac-wpproperty-plugin-icon-300x300.png

exclude:
  - node_modules
  - package.json
  - .idea
  - workspace.xml

sass:
  style: :compressed
  sass_dir: _sass
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

defaults:
  - scope:
      path: "addons"
    values:
      layout: addons
  - scope:
      path: "themes"
    values:
      layout: themes
  - scope:
      path: "docs"
    values:
      layout: docs

plugins:
  - jekyll_get

jekyll_get:
  data: avalon
  json: 'https://api.github.com/repos/wp-property/wp-avalon'

branch: master
